### ISSUE TITLE
Toolbar Button still has default name "Your Button"

### ISSUE THREAD

**Issue by patrickshox** [dwarvesf/session-buddy#5]
To view this, right click on the toolbar & select customize toolbar. The button conventionally has the app name as its label.
<img width="1141" src="https://user-images.githubusercontent.com/47332449/92062559-06387880-ed67-11ea-8678-f3d3f7e5a73f.png">

**Comment by kevinpapst** [comment]
Are you sure this is a valid issue? The "Session Pal" icon next to your red circle seems to be correct.
I have version 1.7 installed and it looks like this:
<img width="1100" alt="Bildschirmfoto 2020-09-23 um 19 55 09" src="https://user-images.githubusercontent.com/533162/94050539-b03f7980-fdd6-11ea-821b-8fa5447cfd21.png">

**Comment by patrickshox** [comment]
Apologies. This issue should be on SearchKey's issues page. I had both GitHub pages open when I was filing this and must have gotten confused.
