### ISSUE TITLE
Privacy Question: Data Collection

### ISSUE THREAD

**Issue by xonic** [dwarvesf/session-buddy#9]
### Question

What exact data are you collecting about users and usage and how do you use it?

### Context

I checked your `PRIVACY_POLICY.md` document which states:
```
Information Collection and Use
The app does NOT use any third party services that may collect information used to identify you.
```

But **Safari claims** that the extension will get the permission to:

```
Read sensitive information from web pages, including passwords, phone numbers and credit cards. Can alter the appearance and behaviour of web pages. This applies to all web pages.

See when you visit all web pages
```
Thanks for clarifying!

**Comment by tieubao** [comment]
@xonic we don't collect any of your data. We store the session data in your computer and don't send it anywhere. We open the source code here, you could check it yourself.

Also the Safari message is true that the extension reads the current website URLs so we can store it for you.

**Comment by xonic** [comment]
Thank you!
